from __future__ import annotations

from datetime import datetime, timedelta, timezone
from zoneinfo import ZoneInfo

import pytest

from api.dependencies import CurrentTenant
from database import crud
from notifications.domain.enums import EventType
from notifications.infrastructure.models import NotificationCategory, NotificationInstance
from tests import factories
from utils.timezone import DEFAULT_TZ
from services import package_service
from services.exceptions import NotFoundError
from services.package_scheduler import regenerate_package_reminders
from services.reminder_definitions import REMINDER_TYPE_PACKAGE_RENEWAL


@pytest.mark.asyncio
async def test_create_package_from_template_generates_lessons_and_reminders(
    db_session,
    current_tenant: CurrentTenant,
    monkeypatch,
):
    reconciliation_calls = []

    async def fake_enqueue(
        session,
        tenant,
        *,
        event_type,
        event_id,
        reason,
        delivery_enabled=None,
        shadow=None,
    ):
        reconciliation_calls.append(
            {
                "event_type": event_type,
                "event_id": event_id,
                "reason": reason,
            }
        )

    monkeypatch.setattr(
        package_service,
        "enqueue_notification_event_reconciliation",
        fake_enqueue,
    )

    learner = await factories.create_learner(db_session)
    template = await factories.create_template(db_session, lesson_count=3)
    await db_session.flush()
    start_local = datetime(2024, 1, 10, 9, 0, tzinfo=DEFAULT_TZ)

    dto = await package_service.create_package_from_template(
        db_session,
        current_tenant,
        learner_id=learner.id,
        template_id=template.id,
        title="Winter Intensive",
        notes="Autogenerated in test",
        start_local=start_local,
        status="active",
    )

    package = await crud.get_lesson_package(db_session, current_tenant, dto.id)
    assert package is not None

    assert dto.total_lessons == template.lesson_count
    assert len(package.lessons) == template.lesson_count
    assert package.end_date == max(lesson.scheduled_at for lesson in package.lessons)

    reminder_types = {instance.rule.reminder_type for instance in package.reminder_instances}
    assert reminder_types, "Expected reminder instances to be generated"
    assert reconciliation_calls == [
        {
            "event_type": EventType.LESSON,
            "event_id": lesson.id,
            "reason": "package_lessons_created",
        }
        for lesson in sorted(package.lessons, key=lambda item: (item.scheduled_at, item.id))
    ] + [
        {
            "event_type": EventType.PACKAGE,
            "event_id": package.id,
            "reason": "package_lessons_created",
        }
    ]


@pytest.mark.asyncio
async def test_create_one_off_lesson_enqueues_reconciliation_without_package_reminders(
    db_session,
    current_tenant: CurrentTenant,
    monkeypatch,
):
    reconciliation_calls = []

    async def fake_enqueue(
        session,
        tenant,
        *,
        event_type,
        event_id,
        reason,
        delivery_enabled=None,
        shadow=None,
    ):
        reconciliation_calls.append(
            {
                "event_type": event_type,
                "event_id": event_id,
                "reason": reason,
            }
        )

    monkeypatch.setattr(
        package_service,
        "enqueue_notification_event_reconciliation",
        fake_enqueue,
    )
    learner = await factories.create_learner(db_session)
    await db_session.flush()

    dto = await package_service.create_one_off_lesson(
        db_session,
        current_tenant,
        learner_id=learner.id,
        scheduled_at=datetime(2026, 6, 1, 12, 0, tzinfo=timezone.utc),
    )
    package = await crud.get_lesson_package(db_session, current_tenant, dto.id)
    assert package is not None

    lesson_ids = [lesson.id for lesson in package.lessons]
    assert len(lesson_ids) == 1
    assert reconciliation_calls == [
        {
            "event_type": EventType.LESSON,
            "event_id": lesson_ids[0],
            "reason": "package_lessons_created",
        },
        {
            "event_type": EventType.PACKAGE,
            "event_id": package.id,
            "reason": "package_lessons_created",
        },
    ]
    reminder_types = {instance.rule.reminder_type for instance in package.reminder_instances}
    assert "payment_week" not in reminder_types
    assert "payment_day" not in reminder_types
    assert "package_renewal" not in reminder_types


@pytest.mark.asyncio
async def test_update_package_normalizes_dates_to_utc(db_session, current_tenant: CurrentTenant):
    learner = await factories.create_learner(db_session)
    package = await factories.create_package(db_session, learner=learner, status="draft")
    await db_session.flush()

    new_start_local = datetime(2024, 2, 1, 15, 30, tzinfo=ZoneInfo("Europe/Moscow"))
    dto = await package_service.update_package(
        db_session,
        current_tenant,
        package.id,
        status="active",
        notes="Updated via service",
        start_date=new_start_local,
    )

    assert dto.status == "active"
    assert dto.notes == "Updated via service"
    assert dto.start_date is not None


@pytest.mark.asyncio
async def test_update_package_to_inactive_cancels_lesson_notifications(
    db_session,
    current_tenant: CurrentTenant,
    monkeypatch,
):
    reconciliation_calls = []

    async def fake_enqueue(
        session,
        tenant,
        *,
        event_type,
        event_id,
        reason,
        delivery_enabled=None,
        shadow=None,
    ):
        reconciliation_calls.append((event_type, event_id, reason))

    monkeypatch.setattr(
        package_service,
        "enqueue_notification_event_reconciliation",
        fake_enqueue,
    )

    learner = await factories.create_learner(db_session)
    package = await factories.create_package(db_session, learner=learner, status="active")
    lesson = await factories.create_lesson(
        db_session,
        package=package,
        scheduled_at=datetime.now(timezone.utc) + timedelta(days=7),
    )
    category = NotificationCategory(
        key=f"update_package_lesson_{id(package)}",
        display_name="Lesson reminder",
    )
    db_session.add(category)
    await db_session.flush()
    instance = NotificationInstance(
        tenant_id=current_tenant.tenant_id,
        category_id=category.id,
        event_type="lesson",
        event_id=lesson.id,
        event_key=f"lesson:{lesson.id}",
        recipient_type="learner",
        recipient_id=learner.id,
        learner_id=learner.id,
        scheduled_for=lesson.scheduled_at - timedelta(hours=1),
        effective_scheduled_for=lesson.scheduled_at - timedelta(hours=1),
        status="scheduled",
        delivery_enabled=True,
        priority="normal",
        channel="telegram",
        dedupe_key=f"update-package-test:{lesson.id}",
    )
    db_session.add(instance)
    await db_session.flush()

    await package_service.update_package(
        db_session,
        current_tenant,
        package.id,
        status="draft",
    )

    await db_session.refresh(instance)
    assert instance.status == "cancelled"
    assert instance.delivery_enabled is False
    assert instance.status_reason == "reconciled:package_updated"
    assert reconciliation_calls == [
        (EventType.LESSON, lesson.id, "package_updated"),
        (EventType.PACKAGE, package.id, "package_updated"),
    ]


@pytest.mark.asyncio
async def test_update_package_can_clear_end_date_and_remove_future_renewal(
    db_session,
    current_tenant: CurrentTenant,
):
    learner = await factories.create_learner(db_session, chat_id=123456)
    package = await factories.create_package(
        db_session,
        learner=learner,
        status="active",
        total_lessons=8,
        schedule_mode="fixed",
        renewal_enabled=True,
    )
    package.end_date = datetime.now(timezone.utc) + timedelta(days=28)
    await factories.create_lesson(
        db_session,
        package=package,
        scheduled_at=package.end_date,
    )
    await db_session.flush()
    await regenerate_package_reminders(db_session, current_tenant, package)
    assert REMINDER_TYPE_PACKAGE_RENEWAL in {
        rule.reminder_type for rule in package.reminder_rules
    }

    dto = await package_service.update_package(
        db_session,
        current_tenant,
        package.id,
        end_date=None,
        end_date_set=True,
    )

    assert dto.end_date is None
    refreshed = await crud.get_lesson_package(db_session, current_tenant, package.id)
    await db_session.refresh(refreshed, attribute_names=["reminder_instances"])
    assert not any(
        instance.active
        and instance.rule.reminder_type == REMINDER_TYPE_PACKAGE_RENEWAL
        for instance in refreshed.reminder_instances
    )
    assert dto.start_date.tzinfo == DEFAULT_TZ

    persisted = await crud.get_lesson_package(db_session, current_tenant, package.id)
    assert persisted is not None
    assert persisted.start_date is not None
    assert persisted.start_date.tzinfo == timezone.utc


@pytest.mark.asyncio
async def test_get_and_list_packages(db_session, current_tenant: CurrentTenant):
    learner = await factories.create_learner(db_session, display_name="Package Learner")
    await factories.create_package(db_session, learner=learner, title="Alpha Package", status="active")
    await db_session.flush()

    packages, total = await package_service.list_packages(
        db_session,
        current_tenant,
        limit=10,
        offset=0,
        learner_id=learner.id,
        status="active",
    )

    assert total == 1
    assert packages[0].learner_name == "Package Learner"

    fetched = await package_service.get_package(db_session, current_tenant, packages[0].id)
    assert fetched.id == packages[0].id


@pytest.mark.asyncio
async def test_delete_package_cancels_future_notifications_before_removing_lessons(
    db_session,
    current_tenant: CurrentTenant,
    monkeypatch,
):
    reconciliation_calls = []

    async def fake_enqueue(
        session,
        tenant,
        *,
        event_type,
        event_id,
        reason,
        delivery_enabled=None,
        shadow=None,
    ):
        reconciliation_calls.append((event_type, event_id, reason))

    monkeypatch.setattr(
        package_service,
        "enqueue_notification_event_reconciliation",
        fake_enqueue,
    )

    learner = await factories.create_learner(db_session)
    package = await factories.create_package(db_session, learner=learner, status="active")
    lesson = await factories.create_lesson(
        db_session,
        package=package,
        scheduled_at=datetime.now(timezone.utc) + timedelta(days=7),
    )
    category = NotificationCategory(
        key=f"delete_package_lesson_{id(package)}",
        display_name="Lesson reminder",
    )
    db_session.add(category)
    await db_session.flush()
    instance = NotificationInstance(
        tenant_id=current_tenant.tenant_id,
        category_id=category.id,
        event_type="lesson",
        event_id=lesson.id,
        event_key=f"lesson:{lesson.id}",
        recipient_type="learner",
        recipient_id=learner.id,
        learner_id=learner.id,
        scheduled_for=lesson.scheduled_at - timedelta(hours=1),
        effective_scheduled_for=lesson.scheduled_at - timedelta(hours=1),
        status="scheduled",
        delivery_enabled=True,
        priority="normal",
        channel="telegram",
        dedupe_key=f"delete-package-test:{lesson.id}",
    )
    db_session.add(instance)
    await db_session.flush()
    instance_id = instance.id
    lesson_id = lesson.id
    package_id = package.id

    await package_service.delete_package(db_session, current_tenant, package_id)

    persisted_instance = await db_session.get(NotificationInstance, instance_id)
    await db_session.refresh(persisted_instance)
    assert persisted_instance.status == "cancelled"
    assert persisted_instance.delivery_enabled is False
    assert persisted_instance.status_reason == "reconciled:package_deleted"
    assert reconciliation_calls == [
        (EventType.LESSON, lesson_id, "package_deleted"),
        (EventType.PACKAGE, package_id, "package_deleted"),
    ]
    with pytest.raises(NotFoundError):
        await package_service.get_package(db_session, current_tenant, package_id)


@pytest.mark.asyncio
async def test_package_not_found_raises(db_session, current_tenant: CurrentTenant):
    with pytest.raises(NotFoundError):
        await package_service.get_package(db_session, current_tenant, 999)

    with pytest.raises(NotFoundError):
        await package_service.delete_package(db_session, current_tenant, 999)


@pytest.mark.asyncio
async def test_create_package_missing_learner(db_session, current_tenant: CurrentTenant):
    with pytest.raises(NotFoundError):
        await package_service.create_package(
            db_session,
            current_tenant,
            learner_id=999,
            title="Missing learner",
        )


@pytest.mark.asyncio
async def test_create_package_from_template_missing_template(db_session, current_tenant: CurrentTenant):
    learner = await factories.create_learner(db_session)
    with pytest.raises(NotFoundError):
        await package_service.create_package_from_template(
            db_session,
            current_tenant,
            learner_id=learner.id,
            template_id=999,
            title="Test",
            notes=None,
            start_local=datetime.now(tz=timezone.utc),
        )

@pytest.mark.asyncio
async def test_create_package_happy_path(db_session, current_tenant: CurrentTenant):
    """Tests successful creation of a simple lesson package."""
    learner = await factories.create_learner(db_session)
    await db_session.flush()
    
    title = "New Simple Package"
    notes = "Some notes here"
    total_lessons = 10

    dto = await package_service.create_package(
        db_session,
        current_tenant,
        learner_id=learner.id,
        title=title,
        notes=notes,
        status="active",
        total_lessons=total_lessons,
    )

    assert dto.id is not None
    assert dto.title == title
    assert dto.notes == notes
    assert dto.learner_id == learner.id
    assert dto.status == "active"
    assert dto.total_lessons == total_lessons

    persisted_package = await crud.get_lesson_package(db_session, current_tenant, dto.id)
    assert persisted_package is not None
    assert persisted_package.title == title
    assert persisted_package.learner_id == learner.id
    assert persisted_package.total_lessons == total_lessons
