services:
  redis:
    image: redis:7-alpine
    restart: always

  applications_bot:
    build: .
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./database:/app/database
