from __future__ import annotations

from datetime import datetime, timedelta, timezone
from itertools import count
from typing import Optional

from sqlalchemy.ext.asyncio import AsyncSession

from database.models import (
    BotUser,
    InviteToken,
    Learner,
    Lesson,
    LessonPackage,
    LessonPackageTemplate,
    ReminderRule,
    ReminderInstance,
    Tenant,
    User,
)

_sequence = count(1)


def _next_suffix() -> int:
    return next(_sequence)


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


async def create_bot_user(
    session: AsyncSession,
    *,
    chat_id: Optional[int] = None,
    username: Optional[str] = None,
    first_name: Optional[str] = None,
    last_name: Optional[str] = None,
    is_bot: bool = False,
) -> BotUser:
    suffix = _next_suffix()
    now = _utc_now()
    instance = BotUser(
        chat_id=chat_id or 10_000 + suffix,
        username=username or f"user{suffix}",
        first_name=first_name or f"Name{suffix}",
        last_name=last_name or f"Surname{suffix}",
        language_code="ru",
        is_bot=is_bot,
        created_at=now,
        updated_at=now,
        last_seen_at=now,
    )
    session.add(instance)
    return instance


async def create_learner(
    session: AsyncSession,
    *,
    display_name: Optional[str] = None,
    notes: Optional[str] = None,
    chat_id: Optional[int] = None,
    notifications_enabled: bool = True,
    archived_at: Optional[datetime] = None,
    tenant_id: int = 1,
) -> Learner:
    bot_user = await create_bot_user(session, chat_id=chat_id)
    now = _utc_now()
    suffix = _next_suffix()
    learner = Learner(
        bot_user=bot_user,
        display_name=display_name or f"Learner {suffix}",
        notes=notes,
        notifications_enabled=notifications_enabled,
        archived_at=archived_at,
        created_at=now,
        tenant_id=tenant_id,
    )
    session.add(learner)
    return learner


async def create_template(
    session: AsyncSession,
    *,
    name: Optional[str] = None,
    lesson_count: int = 4,
    duration_days: Optional[int] = None,
    default_timezone: str = "Europe/Moscow",
    tenant_id: int = 1,
) -> LessonPackageTemplate:
    suffix = _next_suffix()
    now = _utc_now()
    template = LessonPackageTemplate(
        name=name or f"Template {suffix}",
        description="Autogenerated template",
        lesson_count=lesson_count,
        duration_days=duration_days,
        default_timezone=default_timezone,
        default_config={
            "weekly_schedule": [
                {"day": 1, "time": "10:00"},
                {"day": 3, "time": "12:00"},
            ]
        },
        created_at=now,
        updated_at=now,
        tenant_id=tenant_id,
    )
    session.add(template)
    return template


async def create_package(
    session: AsyncSession,
    *,
    learner: Learner,
    template: Optional[LessonPackageTemplate] = None,
    title: Optional[str] = None,
    package_type: str = "package",
    status: str = "draft",
    start_offset_days: int = 0,
    total_lessons: Optional[int] = None,
    notes: Optional[str] = None,
    tenant_id: int = 1,
) -> LessonPackage:
    suffix = _next_suffix()
    now = _utc_now()
    start_date = now + timedelta(days=start_offset_days)
    package = LessonPackage(
        learner=learner,
        template=template,
        package_type=package_type,
        title=title or f"Package {suffix}",
        status=status,
        start_date=start_date,
        timezone=template.default_timezone if template else "Europe/Moscow",
        total_lessons=total_lessons,
        notes=notes,
        created_at=now,
        updated_at=now,
        tenant_id=tenant_id,
    )
    session.add(package)
    return package


async def create_lesson(
    session: AsyncSession,
    *,
    package: LessonPackage,
    scheduled_at: Optional[datetime] = None,
    status: str = "scheduled",
    duration_minutes: Optional[int] = None,
    sequence_index: Optional[int] = None,
    tenant_id: int = 1,
) -> Lesson:
    suffix = _next_suffix()
    now = _utc_now()
    lesson = Lesson(
        package=package,
        scheduled_at=scheduled_at or (now + timedelta(days=suffix)),
        duration_minutes=duration_minutes,
        status=status,
        sequence_index=sequence_index or suffix,
        created_at=now,
        updated_at=now,
        tenant_id=tenant_id,
    )
    session.add(lesson)
    return lesson


async def create_reminder_rule(
    session: AsyncSession,
    *,
    package: LessonPackage,
    lesson: Optional[Lesson] = None,
    reminder_type: str = "lesson_confirm",
    channel: str = "telegram",
    active: bool = True,
    config: Optional[dict] = None,
    tenant_id: int = 1,
) -> ReminderRule:
    rule = ReminderRule(
        package=package,
        lesson=lesson,
        reminder_type=reminder_type,
        config=config or {},
        channel=channel,
        active=active,
        created_at=_utc_now(),
        updated_at=_utc_now(),
        tenant_id=tenant_id,
    )
    session.add(rule)
    return rule


async def create_reminder_instance(
    session: AsyncSession,
    *,
    rule: ReminderRule,
    package: LessonPackage,
    learner: Learner,
    lesson: Optional[Lesson] = None,
    status: str = "scheduled",
    scheduled_at: Optional[datetime] = None,
    active: bool = True,
    payload: Optional[dict] = None,
    chat_identifier: Optional[str] = None,
    tenant_id: int = 1,
) -> ReminderInstance:
    instance = ReminderInstance(
        rule=rule,
        package=package,
        learner=learner,
        lesson=lesson,
        scheduled_for=scheduled_at or (_utc_now() + timedelta(hours=1)),
        status=status,
        payload=payload or {},
        active=active,
        chat_identifier=chat_identifier,
        created_at=_utc_now(),
        updated_at=_utc_now(),
        tenant_id=tenant_id,
    )
    session.add(instance)
    return instance


async def create_tenant(
    session: AsyncSession,
    *,
    name: Optional[str] = None,
    slug: Optional[str] = None,
    contact_email: Optional[str] = None,
    is_active: bool = True,
) -> Tenant:
    suffix = _next_suffix()
    now = _utc_now()
    tenant = Tenant(
        name=name or f"Tenant {suffix}",
        slug=slug or f"tenant-{suffix}",
        contact_email=contact_email or f"tenant{suffix}@example.com",
        is_active=is_active,
        created_at=now,
        updated_at=now,
    )
    session.add(tenant)
    return tenant


async def create_user(
    session: AsyncSession,
    *,
    telegram_id: Optional[int] = None,
    username: Optional[str] = None,
    display_name: Optional[str] = None,
    role: str = "viewer",
    tenant_id: Optional[int] = None,
    email: Optional[str] = None,
    email_normalized: Optional[str] = None,
    password_hash: Optional[str] = None,
) -> User:
    suffix = _next_suffix()
    now = _utc_now()
    user = User(
        telegram_id=telegram_id or (100_000 + suffix),
        username=username or f"user{suffix}",
        email=email,
        email_normalized=email_normalized,
        password_hash=password_hash,
        display_name=display_name or f"User {suffix}",
        role=role,
        tenant_id=tenant_id,
        last_login_at=now,
    )
    session.add(user)
    return user


async def create_invite_token(
    session: AsyncSession,
    *,
    tenant_id: int,
    created_by_user_id: int,
    learner_id: Optional[int] = None,
    token: Optional[str] = None,
    expires_at: Optional[datetime] = None,
    used_at: Optional[datetime] = None,
) -> InviteToken:
    import secrets
    now = _utc_now()
    
    invite_token = InviteToken(
        tenant_id=tenant_id,
        learner_id=learner_id,
        token=token or secrets.token_urlsafe(32),
        expires_at=expires_at or (now + timedelta(days=7)),
        used_at=used_at,
        created_by_user_id=created_by_user_id,
        created_at=now,
    )
    session.add(invite_token)
    await session.flush()  # Ensure we get the ID
    return invite_token


__all__ = [
    "create_bot_user",
    "create_learner",
    "create_template",
    "create_package",
    "create_lesson",
    "create_reminder_rule",
    "create_reminder_instance",
    "create_tenant",
    "create_user",
    "create_invite_token",
]
