"""Add tenant model and tenant_id to relevant tables

Revision ID: 4cd0823487b7
Revises: 20251020_postgres_type_fixes
Create Date: 2025-10-17 13:55:54.779292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cd0823487b7'
down_revision: Union[str, None] = '20251020_postgres_type_fixes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.drop_table('lesson_reminders')

    # Add tenant_id columns as nullable=True first
    op.add_column('applications', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_applications_tenant_id'), 'applications', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'applications', 'tenants', ['tenant_id'], ['id'])

    op.add_column('learners', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_learners_tenant_id'), 'learners', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'learners', 'tenants', ['tenant_id'], ['id'])

    op.add_column('lesson_package_templates', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.alter_column('lesson_package_templates', 'default_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_lesson_package_templates_tenant_id'), 'lesson_package_templates', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'lesson_package_templates', 'tenants', ['tenant_id'], ['id'])

    op.add_column('lesson_packages', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.drop_index('ix_lesson_packages_learner_id', table_name='lesson_packages')
    op.drop_index('ix_lesson_packages_learner_id_status', table_name='lesson_packages')
    op.drop_index('ix_lesson_packages_status', table_name='lesson_packages')
    op.create_index(op.f('ix_lesson_packages_tenant_id'), 'lesson_packages', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'lesson_packages', 'tenants', ['tenant_id'], ['id'])

    op.add_column('lessons', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.drop_index('ix_lessons_package_id', table_name='lessons')
    op.drop_index('ix_lessons_package_id_scheduled_at', table_name='lessons')
    op.drop_index('ix_lessons_scheduled_at', table_name='lessons')
    op.drop_index('ix_lessons_status', table_name='lessons')
    op.create_index(op.f('ix_lessons_tenant_id'), 'lessons', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'lessons', 'tenants', ['tenant_id'], ['id'])

    op.add_column('reminder_instances', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.alter_column('reminder_instances', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_reminder_instances_active', table_name='reminder_instances')
    op.drop_index('ix_reminder_instances_active_scheduled', table_name='reminder_instances')
    op.drop_index('ix_reminder_instances_rule_id', table_name='reminder_instances')
    op.drop_index('ix_reminder_instances_scheduled_for', table_name='reminder_instances')
    op.drop_index('ix_reminder_instances_status', table_name='reminder_instances')
    op.create_index(op.f('ix_reminder_instances_tenant_id'), 'reminder_instances', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'reminder_instances', 'tenants', ['tenant_id'], ['id'])

    op.add_column('reminder_rules', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.alter_column('reminder_rules', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.drop_index('ix_reminder_rules_lesson_id', table_name='reminder_rules')
    op.drop_index('ix_reminder_rules_package_id', table_name='reminder_rules')
    op.create_index(op.f('ix_reminder_rules_tenant_id'), 'reminder_rules', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'reminder_rules', 'tenants', ['tenant_id'], ['id'])

    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])

    # Data migration part
    from sqlalchemy.sql import table, column
    from sqlalchemy import String, Integer, Boolean, DateTime
    from datetime import datetime

    tenant_table = table(
        'tenants',
        column('id', Integer),
        column('name', String),
        column('slug', String),
        column('is_active', Boolean),
        column('created_at', DateTime(timezone=True)),
        column('updated_at', DateTime(timezone=True)),
    )
    op.bulk_insert(tenant_table,
        [{
            'id': 1, 'name': 'Default Tenant', 'slug': 'default', 'is_active': True,
            'created_at': datetime.utcnow(), 'updated_at': datetime.utcnow()
        }]
    )

    op.execute('UPDATE applications SET tenant_id = 1')
    op.execute('UPDATE learners SET tenant_id = 1')
    op.execute('UPDATE lesson_package_templates SET tenant_id = 1')
    op.execute('UPDATE lesson_packages SET tenant_id = 1')
    op.execute('UPDATE lessons SET tenant_id = 1')
    op.execute('UPDATE reminder_instances SET tenant_id = 1')
    op.execute('UPDATE reminder_rules SET tenant_id = 1')
    op.execute('UPDATE users SET tenant_id = 1')

    op.execute("UPDATE users SET tenant_id = NULL WHERE role = 'admin'")

    # Alter columns to be non-nullable
    op.alter_column('applications', 'tenant_id', existing_type=sa.Integer(), nullable=False)
    op.alter_column('learners', 'tenant_id', existing_type=sa.Integer(), nullable=False)
    op.alter_column('lesson_package_templates', 'tenant_id', existing_type=sa.Integer(), nullable=False)
    op.alter_column('lesson_packages', 'tenant_id', existing_type=sa.Integer(), nullable=False)
    op.alter_column('lessons', 'tenant_id', existing_type=sa.Integer(), nullable=False)
    op.alter_column('reminder_instances', 'tenant_id', existing_type=sa.Integer(), nullable=False)
    op.alter_column('reminder_rules', 'tenant_id', existing_type=sa.Integer(), nullable=False)
    # users.tenant_id remains nullable
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'reminder_rules', type_='foreignkey')
    op.drop_index(op.f('ix_reminder_rules_tenant_id'), table_name='reminder_rules')
    op.create_index('ix_reminder_rules_package_id', 'reminder_rules', ['package_id'], unique=False)
    op.create_index('ix_reminder_rules_lesson_id', 'reminder_rules', ['lesson_id'], unique=False)
    op.alter_column('reminder_rules', 'config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('reminder_rules', 'tenant_id')
    op.drop_constraint(None, 'reminder_instances', type_='foreignkey')
    op.drop_index(op.f('ix_reminder_instances_tenant_id'), table_name='reminder_instances')
    op.create_index('ix_reminder_instances_status', 'reminder_instances', ['status'], unique=False)
    op.create_index('ix_reminder_instances_scheduled_for', 'reminder_instances', ['scheduled_for'], unique=False)
    op.create_index('ix_reminder_instances_rule_id', 'reminder_instances', ['rule_id'], unique=False)
    op.create_index('ix_reminder_instances_active_scheduled', 'reminder_instances', ['active', 'scheduled_for'], unique=False)
    op.create_index('ix_reminder_instances_active', 'reminder_instances', ['active'], unique=False)
    op.alter_column('reminder_instances', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('reminder_instances', 'tenant_id')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_tenant_id'), table_name='lessons')
    op.create_index('ix_lessons_status', 'lessons', ['status'], unique=False)
    op.create_index('ix_lessons_scheduled_at', 'lessons', ['scheduled_at'], unique=False)
    op.create_index('ix_lessons_package_id_scheduled_at', 'lessons', ['package_id', 'scheduled_at'], unique=False)
    op.create_index('ix_lessons_package_id', 'lessons', ['package_id'], unique=False)
    op.drop_column('lessons', 'tenant_id')
    op.drop_constraint(None, 'lesson_packages', type_='foreignkey')
    op.drop_index(op.f('ix_lesson_packages_tenant_id'), table_name='lesson_packages')
    op.create_index('ix_lesson_packages_status', 'lesson_packages', ['status'], unique=False)
    op.create_index('ix_lesson_packages_learner_id_status', 'lesson_packages', ['learner_id', 'status'], unique=False)
    op.create_index('ix_lesson_packages_learner_id', 'lesson_packages', ['learner_id'], unique=False)
    op.drop_column('lesson_packages', 'tenant_id')
    op.drop_constraint(None, 'lesson_package_templates', type_='foreignkey')
    op.drop_index(op.f('ix_lesson_package_templates_tenant_id'), table_name='lesson_package_templates')
    op.alter_column('lesson_package_templates', 'default_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('lesson_package_templates', 'tenant_id')
    op.drop_constraint(None, 'learners', type_='foreignkey')
    op.drop_index(op.f('ix_learners_tenant_id'), table_name='learners')
    op.drop_column('learners', 'tenant_id')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_applications_tenant_id'), table_name='applications')
    op.drop_column('applications', 'tenant_id')
    op.create_table('lesson_reminders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chat_identifier', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_recurring', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('days', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lesson_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lesson_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('lead_minutes', sa.INTEGER(), server_default=sa.text('60'), autoincrement=False, nullable=False),
    sa.Column('next_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_notified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_response', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_response_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_decline_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('template_key', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lesson_reminders_pkey')
    )
    op.drop_table('tenants')
    # ### end Alembic commands ###
