"""Add retry_count to reminder_instances

Revision ID: ef476b1e75b2
Revises: 844b00d60f77
Create Date: 2025-11-05 09:14:28.002516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef476b1e75b2'
down_revision: Union[str, None] = '844b00d60f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_packages_tenant_learner_status', table_name='lesson_packages', if_exists=True)
    op.drop_index('ix_lessons_tenant_status_scheduled', table_name='lessons', if_exists=True)
    op.add_column('reminder_instances', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.drop_index('ix_reminders_tenant_status_scheduled', table_name='reminder_instances', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reminders_tenant_status_scheduled', 'reminder_instances', ['tenant_id', 'status', 'scheduled_for'], unique=False)
    op.drop_column('reminder_instances', 'retry_count')
    op.create_index('ix_lessons_tenant_status_scheduled', 'lessons', ['tenant_id', 'status', 'scheduled_at'], unique=False)
    op.create_index('ix_packages_tenant_learner_status', 'lesson_packages', ['tenant_id', 'learner_id', 'status'], unique=False)
    # ### end Alembic commands ###
