"""Shared constants for reminder types and templates."""

LESSON_REMINDER_KIND = 'lesson'
PAYMENT_REMINDER_KIND = 'payment'

PAYMENT_TEMPLATE_WEEK = 'week_before'
PAYMENT_TEMPLATE_DAY = 'day_before'

REMINDER_TYPE_LESSON_CONFIRM = 'lesson_confirm'
REMINDER_TYPE_PAYMENT_WEEK = 'payment_week'
REMINDER_TYPE_PAYMENT_DAY = 'payment_day'
REMINDER_TYPE_HOMEWORK = 'homework'
REMINDER_TYPE_PACKAGE_RENEWAL = 'package_renewal'

DEFAULT_LESSON_CONFIRM_LEAD_MINUTES = 60
HOMEWORK_LEAD_DAYS = 1
HOMEWORK_SEND_HOUR = 10
HOMEWORK_SEND_MINUTE = 0
PACKAGE_RENEWAL_LEAD_DAYS = 14
PACKAGE_RENEWAL_SEND_HOUR = 10
PACKAGE_RENEWAL_SEND_MINUTE = 0

VALID_REMINDER_TYPES = {
    REMINDER_TYPE_LESSON_CONFIRM,
    REMINDER_TYPE_PAYMENT_WEEK,
    REMINDER_TYPE_PAYMENT_DAY,
    REMINDER_TYPE_HOMEWORK,
    REMINDER_TYPE_PACKAGE_RENEWAL,
}
